# Review: Logistic Regression Coefficients

In [1]:
import numpy as np
import pandas as pd

# better, LogisticRegression.fit(...) to find these
vec2 = np.array([[ 1.37239431],
                 [-1.16675093],
                 [-1.32467119],
                 [ 6.59925245]])

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# better, LogisticRegression.predict(...)
def classification_model(row):
    return sigmoid(row @ vec2).round().astype(bool)

# Multi-Class Logistic Regression

In [2]:
animals = ["dog"] * 50 + ["cat"] * 40 + ["mouse"] * 20
weight = np.concatenate((
    np.random.normal(20, 7, 50),
    np.random.normal(10, 3, 40),
    np.random.normal(1, 0.3, 20)
))
df = pd.DataFrame({"weight":weight, "one": 1, "kind": animals})
df

weight  one   kind
0    10.835011    1    dog
1    21.304322    1    dog
2    17.284541    1    dog
3    18.528989    1    dog
4    17.386590    1    dog
..         ...  ...    ...
105   0.532801    1  mouse
106   0.716917    1  mouse
107   1.436854    1  mouse
108   1.240639    1  mouse
109   1.130854    1  mouse

[110 rows x 3 columns]

In [3]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, stratify=df["kind"], train_size=0.5)
train.head()

weight  one   kind
87    7.987801    1    cat
55   12.300825    1    cat
10   17.169456    1    dog
101   0.865147    1  mouse
98    0.927797    1  mouse

In [9]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train[["weight"]], train["kind"])

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [11]:
test.copy()
test["predicted"] = lr.predict(test[["weight"]])
test.head()

weight  one kind predicted
60   4.381950    1  cat       cat
45  16.614620    1  dog       dog
58   8.599523    1  cat       cat
2   17.284541    1  dog       dog
5   24.795626    1  dog       dog

In [13]:
lr.coef_, lr.intercept_

(array([[ 0.16804496],
        [ 1.00460136],
        [-1.17264632]]), array([ 2.1710018 , -9.10402612,  6.93302432]))

In [16]:
coef = np.vstack((lr.coef_.T, lr.intercept_))
coef

array([[ 0.16804496,  1.00460136, -1.17264632],
       [ 2.1710018 , -9.10402612,  6.93302432]])

In [24]:
coef[:, :3]

array([[ 0.16804496,  1.00460136, -1.17264632],
       [ 2.1710018 , -9.10402612,  6.93302432]])

In [36]:
scores = sigmoid(test.iloc[:, :2] @ coef)
scores = scores.set_axis([c+"-score" for c in lr.classes_], axis=1)
scores.head()

cat-score  dog-score   mouse-score
60   0.948209   0.008996  8.574839e-01
45   0.993057   0.999493  3.544717e-06
58   0.973817   0.385816  4.104504e-02
2    0.993791   0.999741  1.615880e-06
5    0.998235   1.000000  2.416633e-10

In [39]:
pd.concat((test, scores), axis=1)

weight  one   kind predicted  cat-score  dog-score   mouse-score
60    4.381950    1    cat       cat   0.948209   0.008996  8.574839e-01
45   16.614620    1    dog       dog   0.993057   0.999493  3.544717e-06
58    8.599523    1    cat       cat   0.973817   0.385816  4.104504e-02
2    17.284541    1    dog       dog   0.993791   0.999741  1.615880e-06
5    24.795626    1    dog       dog   0.998235   1.000000  2.416633e-10
7    11.666024    1    dog       cat   0.984194   0.931864  1.172908e-03
97    0.945565    1  mouse     mouse   0.911323   0.000287  9.970536e-01
44   18.714524    1    dog       dog   0.995111   0.999939  3.021044e-07
35   15.391716    1    dog       dog   0.991486   0.998271  1.487200e-05
93    0.937155    1  mouse     mouse   0.911209   0.000285  9.970824e-01
37   28.374442    1    dog       dog   0.999032   1.000000  3.635913e-12
102   0.926699    1  mouse     mouse   0.911067   0.000282  9.971179e-01
79    2.595805    1    cat     mouse   0.931324   0.001507  9.799459e-01
75    9.506629    1    cat       cat   0.977435   0.609770  1.455887e-02
59   13.760794    1    cat       dog   0.988832   0.991164  1.006742e-04
100   1.259920    1  mouse     mouse   0.915500   0.000394  9.957458e-01
85    9.193572    1    cat       cat   0.976245   0.532915  2.088159e-02
9    32.161651    1    dog       dog   0.999487   1.000000  4.284372e-14
49   16.174171    1    dog       dog   0.992527   0.999211  5.941413e-06
29   21.393291    1    dog       dog   0.996878   0.999996  1.305963e-08
53   10.323254    1    cat       cat   0.980272   0.780182  5.638397e-03
47   22.353171    1    dog       dog   0.997342   0.999998  4.237299e-09
92    1.034090    1  mouse     mouse   0.912518   0.000314  9.967323e-01
80   10.444521    1    cat       cat   0.980662   0.800361  4.894653e-03
40   25.481680    1    dog       dog   0.998427   1.000000  1.080989e-10
30   17.339056    1    dog       dog   0.993848   0.999755  1.515815e-06
67   14.867122    1    cat       dog   0.990709   0.997075  2.751225e-05
14   19.912929    1    dog       dog   0.995999   0.999982  7.410385e-08
21   15.176082    1    dog       dog   0.991175   0.997854  1.915071e-05
106   0.716917    1  mouse     mouse   0.908169   0.000228  9.977450e-01
46   22.641333    1    dog       dog   0.997467   0.999999  3.022288e-09
77   10.269041    1    cat       cat   0.980095   0.770700  6.006259e-03
94    1.489546    1  mouse     mouse   0.918438   0.000496  9.944385e-01
50    7.523298    1    cat       cat   0.968788   0.175649  1.313422e-01
89   10.017465    1    cat       cat   0.979253   0.723028  8.050652e-03
42   18.996249    1    dog       dog   0.995336   0.999954  2.171111e-07
31   24.168762    1    dog       dog   0.998039   1.000000  5.040297e-10
69   10.230365    1    cat       cat   0.979967   0.763761  6.283184e-03
1    21.304322    1    dog       dog   0.996831   0.999995  1.449574e-08
17   32.024509    1    dog       dog   0.999476   1.000000  5.031878e-14
3    18.528989    1    dog       dog   0.994957   0.999926  3.755304e-07
74    5.858785    1    cat       cat   0.959126   0.038483  5.156804e-01
56    9.934847    1    cat       cat   0.978969   0.706104  8.862383e-03
16   17.155184    1    dog       dog   0.993656   0.999706  1.880559e-06
81   11.112783    1    cat       cat   0.982680   0.886943  2.241558e-03
43   18.441758    1    dog       dog   0.994883   0.999919  4.159768e-07
33   29.643978    1    dog       dog   0.999218   1.000000  8.204879e-13
107   1.436854    1  mouse     mouse   0.917772   0.000471  9.947700e-01
66    9.246550    1    cat       cat   0.976451   0.546136  1.964853e-02
25   21.369441    1    dog       dog   0.996865   0.999996  1.343004e-08
64   10.012848    1    cat       cat   0.979237   0.722099  8.093999e-03
84   17.145265    1    cat       dog   0.993645   0.999703  1.902562e-06
76    6.210630    1    cat       cat   0.961383   0.053920  4.134193e-01
99    1.308476    1  mouse     mouse   0.916130   0.000414  9.9549